### ISSUE TITLE
Luacheck linter warnings: W113 (accessing undefined variable), W241 (variable KD_tree is mutated but never accessed)

### ISSUE THREAD

**Issue by 6r1d** [6r1d/kD-tree-lua#2]
The automated part of the translated code cleanup is mostly finished, I'm using `luacheck` to understand what I could've missed.
Also it is used as a part of building some projects, so I can't ignore it.
(*Please excuse the mix of camelCase and underscore notations in my code, I intend to change it all to underscore gradually*.)
Luacheck shows a number of warnings that I don't understand.
What I understand is that they might backfire for me later: I prefer thinking I don't understand code and linter is right: if I'm wrong, I have something to learn, if I do and linter is wrong, it might be translated to a `luacheck` issue later.

For the context, I've read [this list](https://luacheck.readthedocs.io/en/stable/warnings.html) of linter warnings and it still doesn't give me an understanding of a good approach to translation from JS to Lua.

My command is that:

```bash
luacheck kdtree.lua --codes
```

What I see is:

```
Checking kdtree.lua                               7 warnings

    kdtree.lua:183:7: (W241) variable KD_tree is mutated but never accessed
    kdtree.lua:211:17: (W113) accessing undefined variable buildTree
    kdtree.lua:212:18: (W113) accessing undefined variable buildTree
    kdtree.lua:353:21: (W113) accessing undefined variable bf_height
    kdtree.lua:353:43: (W113) accessing undefined variable bf_height
    kdtree.lua:361:12: (W113) accessing undefined variable bf_count
    kdtree.lua:361:34: (W113) accessing undefined variable bf_count

Total: 7 warnings / 0 errors in 1 file
```

**Question 1**: How to best address "variable `KD_tree` is mutated but never accessed"? It is an object I want to be use globally, because it is a primary part of a library for me to use. How to change it, so it can fit well in Minetest mods?

**Question 2**: what logic there is behind "accessing undefined variable"?

> accessing undefined variable `buildTree`

https://github.com/6r1d/kDTree-lua/blob/cf1ffdf0cfabc401009107f7766b2c54fd65731d/kdtree.lua#L189

https://github.com/6r1d/kDTree-lua/blob/cf1ffdf0cfabc401009107f7766b2c54fd65731d/kdtree.lua#L211-L212

*My first assumption*: `luacheck` is "not a fan" of `local` function definitions.
*But* if I approach it like through a normal function definition I get a new "setting non-standard global variable buildTree" and "accessing undefined variable buildTree":

```lua
function buildTree(dimensions, points, depth, parent)
```

>    kdtree.lua:353:21: (W113) accessing undefined variable `bf_height`
>    kdtree.lua:353:43: (W113) accessing undefined variable `bf_height`

https://github.com/6r1d/kDTree-lua/blob/cf1ffdf0cfabc401009107f7766b2c54fd65731d/kdtree.lua#L349

https://github.com/6r1d/kDTree-lua/blob/cf1ffdf0cfabc401009107f7766b2c54fd65731d/kdtree.lua#L353

It is the same with `bf_count`.

>    kdtree.lua:361:12: (W113) accessing undefined variable `bf_count`
>    kdtree.lua:361:34: (W113) accessing undefined variable `bf_count`

https://github.com/6r1d/kDTree-lua/blob/cf1ffdf0cfabc401009107f7766b2c54fd65731d/kdtree.lua#L357

https://github.com/6r1d/kDTree-lua/blob/cf1ffdf0cfabc401009107f7766b2c54fd65731d/kdtree.lua#L361

**Comment by OgelGames** [comment]
1: If you want it to be global, then it can't be local at the same time. Remove the `local` before it, and then add it as a global to the luacheckrc (otherwise it will complain about the global).

The other option is to put a `return KD_tree` at the end of the file, and then use `local KD_tree = dofile("path/to/kdtree.lua")` when you want to use it.

2: Recursive functions can't be defined like that, they need to be like this:
```lua
local function buildTree(dimensions, points, depth, parent)
```
Same for the other recursive functions.

**Comment by 6r1d** [comment]
I'll go with `return KD_tree` approach, seems like it'll work.
Thanks, @OgelGames, it is resolved!
